/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:fde352e4-f905-4738-9d4e-fe6fddcaaf70",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ESQ8plQSB",
    "aws_user_pools_web_client_id": "sdnf2dqc2au7dr7ojo8nfh9k2",
    "oauth": {}
};


export default awsmobile;
